import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import ReactQueryProvider from '@/components/providers/ReactQueryProvider';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { UserProvider } from '@/components/providers/UserProvider';
import { getUser } from '@/lib/auth';
import { Toaster } from 'sonner';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const userPromise = getUser();

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} bg-[#F7F7F7] font-semibold text-[#393939] antialiased`}
            >
                <ReactQueryProvider>
                    <UserProvider userPromise={userPromise}>
                        {children}
                        <ReactQueryDevtools />
                        <Toaster richColors position="top-center" />
                    </UserProvider>
                </ReactQueryProvider>
            </body>
        </html>
    );
}
